workflows:
 patrol-android-tests:
   name: Patrol Android Tests
   instance_type: mac_mini_m2
   max_build_duration: 120
   environment:
     flutter: stable
     groups:
       - patrol_config
   scripts:
     - name: Install Flutter packages
       script: |
         flutter pub get
         
     - name: Install Patrol CLI  
       script: |
         dart pub global activate patrol_cli
         
     - name: Check available devices
       script: |
         flutter devices
         
     - name: Run Patrol tests
       script: |
         patrol test integration_test/successful_login_test.dart
       
   artifacts:
     - patrol-results/**/*.png
     - patrol-results/**/*.xml
     - patrol-results/**/video.mp4