workflows:
 patrol-android-tests:
   name: Patrol Android Tests
   instance_type: mac_mini_m2
   max_build_duration: 120
   environment:
     flutter: stable
     groups:
       - patrol_config
   scripts:
     - name: Set up Android SDK
       script: |
         $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;30.0.3" "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;arm64-v8a"
         
     - name: Create and start emulator
       script: |
         echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n android_emulator -k "system-images;android-30;google_apis;arm64-v8a" --force
         $ANDROID_HOME/emulator/emulator -avd android_emulator -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect &
         adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done'
         flutter devices
         
     - name: Run tests
       script: |
         flutter pub get
         dart pub global activate patrol_cli
         patrol test integration_test/successful_login_test.dart -d android_emulator --debug
           
   artifacts:
     - patrol-results/**/*.png
     - patrol-results/**/*.xml
     - patrol-results/**/video.mp4