workflows:
  patrol-android-tests:
    name: Patrol Android Tests
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - patrol_config
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
          
      - name: Install Patrol CLI
        script: dart pub global activate patrol_cli
          
      - name: Run Android Integration Tests
        script: |
          patrol test android \
            --debug \
            --target integration_test/successful_login_test.dart
            
    artifacts:
      - patrol-results/**/*.png
      - patrol-results/**/*.xml
      - patrol-results/**/video.mp4