workflows:
  patrol-android-tests:
    name: Patrol Android Tests
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - patrol_config
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
          
      - name: Install Patrol CLI
        script: dart pub global activate patrol_cli
        
      - name: Start Android emulator
        script: |
          echo "Starting emulator..."
          $ANDROID_SDK_ROOT/emulator/emulator -avd emulator -no-window -no-audio -no-boot-anim -accel on &
          echo "Waiting for device to complete boot..."
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
          echo "Emulator is ready!"
          
      - name: Run Android Integration Tests
        script: |
          echo "Available devices:"
          flutter devices
          echo "Starting Patrol tests..."
          patrol test integration_test/successful_login_test.dart \
            --target android \
            --debug \
            --timeout=15m \
            --verbose
            
    artifacts:
      - patrol-results/**/*.png
      - patrol-results/**/*.xml
      - patrol-results/**/video.mp4