workflows:
  patrol-android-tests:
    name: Patrol Android Tests
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - patrol_config
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: flutter pub get
          
      - name: Install Patrol CLI
        script: dart pub global activate patrol_cli
        
      - name: Create emulator
        script: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;google_apis;x86_64"
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test_device -k "system-images;android-30;google_apis;x86_64"
      
      - name: Start emulator and run tests
        script: |
          $ANDROID_HOME/emulator/emulator -avd test_device -no-audio -no-window &
          adb wait-for-device
          patrol test integration_test/successful_login_test.dart -d test_device --debug
            
    artifacts:
      - patrol-results/**/*.png
      - patrol-results/**/*.xml
      - patrol-results/**/video.mp4