workflows:
  android-integration-test:
    name: Android Integration Test
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
          dart pub global activate patrol_cli
          
      - name: Start Android emulator
        script: |
          flutter emulators
          $ANDROID_SDK_ROOT/emulator/emulator -avd emulator -no-audio -no-window &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done'
          echo "Emulator is ready!"
          flutter devices

      - name: Run Patrol tests
        script: |
          patrol test integration_test/successful_login_test.dart -d emulator-5554 --debug
          
    artifacts:
      - patrol-results/**/*.png
      - patrol-results/**/*.xml
      - patrol-results/**/video.mp4