workflows:
  ios-integration-test:
    name: iOS Integration Test
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
          dart pub global activate patrol_cli
          
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
          
      - name: Start iOS Simulator
        script: |
          xcrun simctl boot "iPhone 15" # Using iPhone 15 from the list
          xcrun simctl list devices
          flutter devices
          
      - name: Run Patrol tests
        script: |
          patrol test -t integration_test/successful_login_test.dart -d "iPhone 15" --debug
          
    artifacts:
      - patrol-results/**/*.png
      - patrol-results/**/*.xml
      - patrol-results/**/video.mp4