workflows:
  patrol-android-tests:
    name: Patrol Android Tests
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - patrol_config
      vars:
        AVD_NAME: android_emulator
    scripts:
      - name: Install Android SDK tools
        script: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "emulator" "build-tools;30.0.3" "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;arm64-v8a"

      - name: Create emulator
        script: |
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n $AVD_NAME -k "system-images;android-30;google_apis;arm64-v8a" --force

      - name: Start emulator
        script: |
          $ANDROID_HOME/emulator/emulator -avd $AVD_NAME -no-window -no-audio -gpu swiftshader_indirect -accel off -verbose &
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 3; done'

      - name: List available devices
        script: |
          flutter devices

      - name: Run Patrol tests
        script: |
          flutter pub get
          dart pub global activate patrol_cli
          patrol test integration_test/successful_login_test.dart -d emulator --debug

    artifacts:
      - patrol-results/**/*.png
      - patrol-results/**/*.xml
      - patrol-results/**/video.mp4
