workflows:
  patrol-android-tests:
    name: Patrol Android Tests
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - patrol_config
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
          
      - name: Install Patrol CLI
        script: dart pub global activate patrol_cli
        
      - name: Create and start Android emulator
        script: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-30;google_apis;x86_64"
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test_emulator -k "system-images;android-30;google_apis;x86_64"
          $ANDROID_HOME/emulator/emulator -avd test_emulator -no-window -no-audio &
          adb wait-for-device
          
      - name: Run Android Integration Tests
        script: |
          patrol test \
            integration_test/successful_login_test.dart \
            -d emulator-5554 \
            --debug
            
    artifacts:
      - patrol-results/**/*.png
      - patrol-results/**/*.xml
      - patrol-results/**/video.mp4