workflows:
  patrol-android-tests:
    name: Patrol Android Tests
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - patrol_config
      android:
        image: android-31
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
          
      - name: Install Patrol CLI
        script: dart pub global activate patrol_cli

      - name: Start Android emulator
        script: |
          cd $ANDROID_HOME/tools
          emulator @Pixel_4_API_31 -no-audio -no-window &
          adb wait-for-device
          adb shell input keyevent 82
          
      - name: Run Android Integration Tests
        script: |
          patrol test integration_test/successful_login_test.dart \
            --target android \
            --debug
            
    artifacts:
      - patrol-results/**/*.png
      - patrol-results/**/*.xml
      - patrol-results/**/video.mp4